language: python

python:
  - "2.7"

env:
  - TORNADO_VERSION=5.0

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install tornado>=$TORNADO_VERSION"
  - "pip install pytest"
  - "pip install pytest-pep8"
  - "pip install pytest-flake8"
  - python setup.py install

# command to run tests (no tests yet)
script:
  - pytest --pep8 --flake8
